stages:
  download:
    cmd: python download.py
    deps:
    - download.py
    params:
    - download.base_url
    - download.html_filename
    - download.n_locs
    - global.YYYY
    - global.download_dir
    - global.filter_cols
    outs:
    - ncei_data/
  prepare:
    cmd: python prepare.py
    deps:
    - ncei_data
    - prepare.py
    params:
    - global.YYYY
    - global.download_dir
    - global.filter_cols
    - global.hourly_cols
    - prepare.gt_dir
    outs:
    - data/gt
  process:
    cmd: python process.py
    deps:
    - ncei_data
    - process.py
    params:
    - global.download_dir
    - global.hourly_cols
    - prepare.gt_dir
    - process.calc_dir
    outs:
    - data/calculated
  evaluate:
    cmd: python evaluate.py
    deps:
    - evaluate.py
    params:
    - global.filter_cols
    - prepare.gt_dir
    outs:
    - R2results.csv
